name: Update Games Table ETL

on:
  schedule:
    - cron: "0 14 * * *"

jobs:
  update-games:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Debug installation
      run: cat requirements.txt
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Update games table
      env:
        SUPABASE_URL: ${{secrets.SUPABASE_URL}}
        SUPABASE_SERVICE_KEY: ${{secrets.SUPABASE_SERVICE_KEY}}
      run: python etl/update_games.py
